// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrvqpnxxmijgxefjifpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlydnFwbnh4bWlqZ3hlZmppZnByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNzE2MzIsImV4cCI6MjA4Njg0NzYzMn0.8wBAStGubeeuFmsRDBcEeb_vd4ak3ku_DNHH4Z1ceeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});